const products=[
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    },
    {
        id:1,
        name:"sss",
        price:50,
        rating:4,
        Image:"s",
        description:""
    }
]

export default products